-- Utilizado MySQL

CREATE DATABASE IF NOT exists turismo;
use turismo;

-- CREACION DE TABLAS
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `VISITANTE`(
`DNI` VARCHAR(25),
`NOMBRE` VARCHAR(25),
`DOMICILIO` VARCHAR(25),
`PROFESION` VARCHAR(25));

ALTER TABLE `VISITANTE`
ADD PRIMARY KEY (`DNI`),
ADD KEY(`DNI`);

CREATE TABLE `EXCURSION`(
`CODEXCURSION` INT(15) ,
`FECHA` DATE,
`HORA` TIME,
`APIE` VARCHAR(25),
`CODALOJAMIENTO` INT(15));

ALTER TABLE `EXCURSION`
ADD PRIMARY KEY (`CODEXCURSION`),
ADD KEY (`CODEXCURSION`);

CREATE TABLE `E_V`(
`CODEXCURSION` INT(15),
`DNI` VARCHAR(25));

ALTER TABLE `E_V`
ADD KEY (`CODEXCURSION`),
ADD CONSTRAINT e_v_ibf_k1 FOREIGN KEY (`CODEXCURSION`) REFERENCES `EXCURSION`(`CODEXCURSION`) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD KEY(`DNI`),
ADD CONSTRAINT e_v_ibf_k2 FOREIGN KEY (`DNI`) REFERENCES `VISITANTE`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `ALOJAMIENTO`(
`CODALOJAMIENTO` INT(15) ,
`CATEGORIA` VARCHAR(25),
`CAPACIDAD` INT(15),
`CODPN` INT(15));

ALTER TABLE `ALOJAMIENTO`
ADD PRIMARY KEY (`CODALOJAMIENTO`),
ADD KEY (`CODALOJAMIENTO`);

ALTER TABLE `EXCURSION`
ADD CONSTRAINT excursion_ibf_k1 FOREIGN KEY (`CODALOJAMIENTO`) REFERENCES `ALOJAMIENTO`(`CODALOJAMIENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `COMUNIDADAUTONOMA`(
`CODCA` INT(15),
`NOMBRE` VARCHAR(25),
`ORGRESPONSABLE` VARCHAR(25));

ALTER TABLE `COMUNIDADAUTONOMA`
ADD PRIMARY KEY (`CODCA`),
ADD KEY(`CODCA`);

CREATE TABLE `A_V`(
`CODALOJAMIENTO` INT(15),
`DNI` VARCHAR(25),
`FECHAINICIO` DATE,
`FECHAFIN`DATE);

ALTER TABLE `A_V`
ADD KEY (`CODALOJAMIENTO`),
ADD CONSTRAINT a_v_ibf_k1 FOREIGN KEY (`CODALOJAMIENTO`) REFERENCES `ALOJAMIENTO`(`CODALOJAMIENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD KEY(`DNI`),
ADD CONSTRAINT a_v_ibf_k2 FOREIGN KEY (`DNI`) REFERENCES `VISITANTE`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD PRIMARY KEY (`FECHAINICIO`),
ADD KEY (`FECHAINICIO`);

CREATE TABLE `ENTRADA`(
`CODENTRADA` INT(15) ,
`CODPN` INT(15));

ALTER TABLE `ENTRADA`
ADD PRIMARY KEY (`CODENTRADA`),
ADD KEY (`CODENTRADA`);

CREATE TABLE `PARQUENATURAL`(
`CODPN` INT(15),
`NOMBRE` VARCHAR(25),
`FECHADECLARACION` DATE);

ALTER TABLE `PARQUENATURAL`
ADD PRIMARY KEY (`CODPN`),
ADD KEY(`CODPN`);

ALTER TABLE `ALOJAMIENTO`
ADD CONSTRAINT alojamiento_ibf_k1 FOREIGN KEY (`CODPN` ) REFERENCES `PARQUENATURAL`(`CODPN` ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `ENTRADA`
ADD CONSTRAINT entrada_ibf_k1 FOREIGN KEY (`CODPN` ) REFERENCES `PARQUENATURAL`(`CODPN` ) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `CA_PN`(
`CODCA` INT(15),
`CODPN` INT(15),
`SUPERFICIE` INT(15));

ALTER TABLE `CA_PN`
ADD KEY (`CODCA`),
ADD CONSTRAINT ca_pn_ibf_k1 FOREIGN KEY (`CODCA`) REFERENCES `COMUNIDADAUTONOMA`(`CODCA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD KEY(`CODPN`),
ADD CONSTRAINT ca_pn_ibf_k2 FOREIGN KEY (`CODPN`) REFERENCES `PARQUENATURAL`(`CODPN`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `ESPECIE`(
`CODESPECIE` INT(15),
`NOMBRECIENTIFICO` VARCHAR(25),
`NOMBREVULGAR` VARCHAR(25));

ALTER TABLE `ESPECIE`
ADD PRIMARY KEY (`CODESPECIE`),
ADD KEY (`CODESPECIE`);

CREATE TABLE `E_A`(
`CODESPECIE` INT(15),
`NOMBREA` VARCHAR(25),
`CANTIDIVIDUOS` INT(15));

ALTER TABLE `E_A`
ADD KEY (`CODESPECIE`),
ADD CONSTRAINT e_a_ibf_k1 FOREIGN KEY (`CODESPECIE`) REFERENCES `ESPECIE`(`CODESPECIE`) ON DELETE NO ACTION ON UPDATE NO ACTION;


CREATE TABLE `ANIMAL`(
`CODESPECIE` INT(15),
`ALIMENTACION` VARCHAR(25),
`PERIODOCELO` VARCHAR(25));

ALTER TABLE `ANIMAL`
ADD KEY (`CODESPECIE`),
ADD CONSTRAINT animal_ibf_k1 FOREIGN KEY (`CODESPECIE`) REFERENCES `ESPECIE`(`CODESPECIE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `VEGETAL`(
`CODESPECIE` INT(15),
`FLORACION` VARCHAR(25),
`PERIODOFLORACION` VARCHAR(25));

ALTER TABLE `VEGETAL`
ADD KEY (`CODESPECIE`),
ADD CONSTRAINT vegetal_ibf_k1 FOREIGN KEY (`CODESPECIE`) REFERENCES `ESPECIE`(`CODESPECIE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `MINERAL`(
`CODESPECIE` INT(15),
`TIPO` VARCHAR(25));

ALTER TABLE `MINERAL`
ADD KEY (`CODESPECIE`),
ADD CONSTRAINT mineral_ibf_k1 FOREIGN KEY (`CODESPECIE`) REFERENCES `ESPECIE`(`CODESPECIE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `PERSONAL`(
`DNI` VARCHAR(25),
`NSS` INT(25),
`NOMBRE` VARCHAR(25),
`DIRECCION` VARCHAR(25),
`TFNODOMICILIO` INT(15),
`TFNMOVIL` INT(15),
`SUELDO` INT(15),
`CODPN` INT(15));

ALTER TABLE `PERSONAL`
ADD PRIMARY KEY (`DNI`),
ADD KEY (`DNI`),
ADD UNIQUE (`NSS`),
ADD CONSTRAINT personal_ibf_k1 FOREIGN KEY (`CODPN`) REFERENCES `PARQUENATURAL`(`CODPN`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `CONSERVADOR`(
`DNI` VARCHAR(25),
`TAREA` VARCHAR(25),
`NOMBREA` VARCHAR(25));

ALTER TABLE `CONSERVADOR`
ADD KEY (`DNI`),
ADD CONSTRAINT conservador_ibf_k1 FOREIGN KEY (`DNI`) REFERENCES `PERSONAL`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `VIGILANTE`(
`DNI` VARCHAR(25),
`NOMBREA` VARCHAR(25));

ALTER TABLE `VIGILANTE`
ADD PRIMARY KEY (`DNI`),
ADD KEY (`DNI`),
ADD CONSTRAINT vigilante_ibf_k1 FOREIGN KEY (`DNI`) REFERENCES `PERSONAL`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `INVESTIGADOR`(
`DNI` VARCHAR(25),
`TITULACION` VARCHAR(25));

ALTER TABLE `INVESTIGADOR`
ADD KEY (`DNI`),
ADD CONSTRAINT investigador_ibf_k1 FOREIGN KEY (`DNI`) REFERENCES `PERSONAL`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `GESTOR`(
`DNI` VARCHAR(25),
`CODENTRADA` INT(15));

ALTER TABLE `GESTOR`
ADD KEY (`DNI`),
ADD CONSTRAINT gestor_ibf_k1 FOREIGN KEY (`DNI`) REFERENCES `PERSONAL`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT gestor_ibf_k2 FOREIGN KEY (`CODENTRADA`) REFERENCES `ENTRADA`(`CODENTRADA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `AREA`(
`NOMBREA` VARCHAR(25),
`EXTENSION` INT(15),
`CODPN` INT(15));

ALTER TABLE `AREA`
ADD PRIMARY KEY (`NOMBREA`),
ADD KEY (`NOMBREA`),
ADD CONSTRAINT area_ibf_k1 FOREIGN KEY (`CODPN`) REFERENCES `PARQUENATURAL`(`CODPN`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `E_A`
ADD CONSTRAINT e_a_ibf_k2 FOREIGN KEY (`NOMBREA`) REFERENCES `AREA`(`NOMBREA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `VIGILANTE`
ADD CONSTRAINT vigilante_ibf_k2 FOREIGN KEY (`NOMBREA`) REFERENCES `AREA`(`NOMBREA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `CONSERVADOR`
ADD CONSTRAINT conservador_ibf_k2 FOREIGN KEY (`NOMBREA`) REFERENCES `AREA`(`NOMBREA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `VEHICULO`(
`MATRICULA` INT(15),
`TIPO` VARCHAR(25),
`DNI` INT(15));

ALTER TABLE `VEHICULO`
ADD PRIMARY KEY (`MATRICULA`),
ADD KEY (`MATRICULA`),
ADD CONSTRAINT vehiculo_ibf_k1 FOREIGN KEY (`DNI`) REFERENCES `VIGILANTE`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `I_P`(
`CODPROY` INT(15),
`DNI` INT(15));

ALTER TABLE `I_P`
ADD KEY (`CODPROY`),
ADD KEY (`DNI`),
ADD CONSTRAINT i_p_ibf_k2 FOREIGN KEY (`DNI`) REFERENCES `INVESTIGADOR`(`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE `PROYECTO`(
`CODPROY` INT(15),
`PRESUPUESTO` INT(15),
`FECHAINICIO` DATE,
`FECHAFIN` DATE,
`CODESPECIE` INT(15));

ALTER TABLE `PROYECTO`
ADD PRIMARY KEY (`CODPROY`),
ADD KEY (`CODPROY`),
ADD CONSTRAINT proyecto_ibf_k1 FOREIGN KEY (`CODESPECIE`) REFERENCES `ESPECIE`(`CODESPECIE`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `I_P`
ADD CONSTRAINT i_p_ibf_k1 FOREIGN KEY (`CODPROY`) REFERENCES `PROYECTO`(`CODPROY`) ON DELETE NO ACTION ON UPDATE NO ACTION;

SET FOREIGN_KEY_CHECKS = 1;




