-- Utilizado MySQL

CREATE DATABASE IF NOT exists turismo;
use turismo;

-- CREACION DE TABLAS

CREATE TABLE `VISITANTE`(
`DNI` VARCHAR(25),
`NOMBRE` VARCHAR(25),
`DOMICILIO` VARCHAR(25),
`PROFESION` VARCHAR(25));

ALTER TABLE `VISITANTE`
ADD PRIMARY KEY (`DIN`),
ADD KEY(`DIN`);

CREATE TABLE `EXCURSION`(
`CODEXCURSION` INT(15) ,
`FECHA` DATE,
`HORA` TIME,
`APIE` VARCHAR(25),
`CODALOJAMIENTO` INT(15));

ALTER TABLE `EXCURSION`
ADD PRIMARY KEY (`CODEXCURSION`),
ADD KEY (`CODEXCURSION`),
ADD CONSTRAINT excursion_ibf_k1 FOREIGN KEY (`CODALOJAMIENTO`) REFERENCES `ALOJAMIENTO`(`CODALOJAMIENTO`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `E_V`(
`CODEXCURSION` INT(15),
`DNI` VARCHAR(25));

ALTER TABLE `E_V`
ADD PRIMARY KEY (`CODEXCURSION`),
ADD KEY (`CODEXCURSION`),
ADD CONSTRAINT e_v_ibf_k1 FOREIGN KEY (`CODEXCURSION`) REFERENCES `EXCURSION`(`CODEXCURSION`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD PRIMARY KEY (`DIN`),
ADD KEY(`DIN`),
ADD CONSTRAINT e_v_ibf_k2 FOREIGN KEY (`DIN`) REFERENCES `VISITANTE`(`DIN`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `ALOJAMIENTO`(
`CODALOJAMIENTO` INT(15) ,
`CATEGORIA` VARCHAR(25),
`CAPACIDAD` INT(15),
`CODPN` INT(15));

ALTER TABLE `ALOJAMIENTO`
ADD PRIMARY KEY (`CODALOJAMIENTO`),
ADD KEY (`CODALOJAMIENTO`),
ADD CONSTRAINT alojamiento_ibf_k1 FOREIGN KEY (`CODPN` ) REFERENCES `PARQUENATURAL`(`CODPN` ) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `COMUNIDADAUTONOMA`(
`CODCA` INT(15),
`NOMBRE` VARCHAR(25),
`ORGRESPONSABLE` VARCHAR(25));

ALTER TABLE `COMUNIDADAUTONOMA`
ADD PRIMARY KEY (`CODCA`),
ADD KEY(`CODCA`);

CREATE TABLE `A_V`(
`CODALOJAMIENTO` INT(15),
`DNI` VARCHAR(25),
`FECHAINICIO` DATE,
`FECHAFIN`DATE);

ALTER TABLE `A_V`
ADD PRIMARY KEY (`CODALOJAMIENTO`),
ADD KEY (`CODALOJAMIENTO`),
ADD CONSTRAINT a_v_ibf_k1 FOREIGN KEY (`CODALOJAMIENTO`) REFERENCES `ALOJAMIENTO`(`CODALOJAMIENTO`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD PRIMARY KEY (`DIN`),
ADD KEY(`DIN`),
ADD CONSTRAINT a_v_ibf_k2 FOREIGN KEY (`DIN`) REFERENCES `VISITANTE`(`DIN`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD PRIMARY KEY (`FECHAINICIO`),
ADD KEY (`FECHAINICIO`);

CREATE TABLE `ENTRADA`(
`CODENTRADA` INT(15) ,
`CODPN` INT(15));

ALTER TABLE `ENTRADA`
ADD PRIMARY KEY (`CODENTRADA`),
ADD KEY (`CODENTRADA`),
ADD CONSTRAINT entrada_ibf_k1 FOREIGN KEY (`CODPN` ) REFERENCES `PARQUENATURAL`(`CODPN` ) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `PARQUENATURAL`(
`CODPN` INT(15),
`NOMBRE` VARCHAR(25),
`FECHADECLARACION` DATE);

ALTER TABLE `PARQUENATURAL`
ADD PRIMARY KEY (`CODPN`),
ADD KEY(`CODPN`);

CREATE TABLE `CA_PN`(
`CODCA` INT(15),
`CODPN` INT(15),
`SUPERFICIE` INT(15));

ALTER TABLE `CA_PN`
ADD PRIMARY KEY (`CODCA`),
ADD KEY (`CODCA`),
ADD CONSTRAINT a_v_ibf_k1 FOREIGN KEY (`CODCA`) REFERENCES `COMUNIDADAUTONOMA`(`CODCA`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD PRIMARY KEY (`CODPN`),
ADD KEY(`CODPN`),
ADD CONSTRAINT a_v_ibf_k2 FOREIGN KEY (`CODPN`) REFERENCES `PARQUENATURAL`(`CODPN`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `ESPECIE`(
`CODESPECIE` INT(15),
`NOMBRECIENTIFICO` VARCHAR(25),
`NOMBREVULGAR` VARCHAR(25));

ALTER TABLE `ESPECIE`
ADD PRIMARY KEY (`CODESPECIE`),
ADD KEY (`CODESPECIE`);






